var chai=require('chai');var expect=chai.expect;var should=chai.should;var sinon=require('sinon');var proxyquire=require('proxyquire');var _=require('lodash');var moment=require('moment');var util=require(__dirname+'/../../core/util');var config=util.getConfig();var dirs=util.dirs();var TRADES=require('./data/bitstamp_trades.json');return; var FakeExchange=function(){};FakeExchange.prototype={transactions:function(since,handler,descending){handler(null,TRADES);}}
var transactionsSpy=sinon.spy(FakeExchange.prototype,'transactions');spoofer={bitstamp:FakeExchange}
describe('exchanges/bitstamp',function(){var Bitstamp=proxyquire(dirs.gekko+'exchange/wrappers/bitstamp',spoofer);var bs;it('should instantiate',function(){bs=new Bitstamp(config.watch);});it('should correctly fetch historical trades',function(){bs.getTrades(null,_.noop,false);expect(transactionsSpy.callCount).to.equal(1);var args=transactionsSpy.lastCall.args;expect(args.length).to.equal(2);expect(args[0]).to.equal('btcusd');});it('should retry on exchange error',function(){var ErrorFakeExchange=function(){};ErrorFakeExchange.prototype={transactions:function(since,handler,descending){handler('Auth error');}}
spoofer={bitstamp:ErrorFakeExchange}
var ErroringBitstamp=proxyquire(dirs.exchanges+'bitstamp',spoofer);var ebs=new ErroringBitstamp(config.watch);ebs.retry=_.noop;var retrySpy=sinon.spy(ebs,'retry');ebs.getTrades(null,_.noop)
expect(retrySpy.callCount).to.equal(1);var args=retrySpy.lastCall.args;expect(args[1].length).to.equal(2);expect(args[1][0]).to.equal(null);})
it('should correctly parse historical trades',function(done){var check=function(err,trades){expect(err).to.equal(null);expect(trades.length).to.equal(TRADES.length);var oldest=_.first(trades);var OLDEST=_.last(TRADES);expect(oldest.tid).to.equal(+OLDEST.tid);expect(oldest.price).to.equal(+OLDEST.price);expect(oldest.amount).to.equal(+OLDEST.amount);expect(oldest.date).to.equal(OLDEST.date);done();}
bs.getTrades(null,check,false);});});
/*
The MIT License (MIT)
Copyright (c) 2014-2017 Mike van Rossum mike@mvr.me
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/